using AIGames.BlockBattle.Kubisme.Communication;
using NUnit.Framework;
using System;
using System.Linq;

namespace AIGames.BlockBattle.Kubisme.UnitTests.DecisionMaking
{
	public class NodeDescisionMakerTest
	{
		[Test]
		public void GetMove_BugOneToLeftToMuch_LeftDrop()
		{
			var field = Field.Create(0, 0, @"
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
X.......XX
XXX.....XX");
			var dm = new NodeDecisionMaker()
			{
				Evaluator = new SimpleEvaluator()
				{
					Parameters = SimpleParameters.GetDefault()
				},
				Points = new int[10],
				Generator = new MoveGenerator(),
				MaximumDepth = 1,
			};

			var act = dm.GetMove(field, Block.Z, Block.S);
			var exp = BlockPath.Create(ActionType.Left, ActionType.Drop);

			Assert.AreEqual(exp, act);
		}
	}
}
